apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    app: mysql
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi  # allocate the space you want
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/mysql-data # set the path you want on your machine
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # how much is claimed
