apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pma
  name: pma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pma
  template:
    metadata:
      labels:
        app: pma
    spec:
      containers:
      - image: phpmyadmin/phpmyadmin
        name: phpmyadmin
        ports:
        - containerPort: 80
        env:
        - name: PMA_HOST
          value: mysql
        - name: PMA_PORT
          value: "3306"
        - name: PHPMYADMIN_ALLOW_ARBITRARY_SERVER
          value: "true"
        - name: DATABASE_ENABLE_SSL
          value: "no"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: pma-service
spec:
  type: LoadBalancer
  selector:
    app: pma
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
